version: '3.9'

services:
  redis:
    image: redis:alpine
  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
  celery:
    container_name: celery
    build: .
    command: celery -A rocket worker -l info
    volumes:
      - .:/app
    depends_on:
      - django

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A rocket beat -l info
    volumes:
      - .:/app
    depends_on:
      - django
  flower:
    container_name: flower
    build: .
    ports:
      - 5555:5555
    command: celery -A rocket flower
    volumes:
      - .:/app
    depends_on:
      - celery
