# Generated by Django 4.2 on 2025-04-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
