# Generated by Django 4.2 on 2025-04-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='network_node',
        ),
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='network_nodes', to='main.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_network_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='main.networknode', verbose_name='Звено сети'),
        ),
    ]
