# Generated by Django 4.2 on 2025-04-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_network_node_networknode_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='products',
        ),
    ]
