# Generated by Django 4.2 on 2025-04-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_networknode_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='network_nodes', to='main.product'),
        ),
    ]
