# Generated by Django 4.2 on 2025-04-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
